-- 300개의 사전 분석된 어법 대립쌍 데이터
-- 17개 카테고리로 분류된 고품질 어법 오류 패턴

INSERT INTO public.categorized_veritas_pairs (correct_form, incorrect_form, category, explanation, usage_count) VALUES

-- 1. verb_form (동사 형태)
('interested', 'interesting', 'verb_form', '-ed형 감정 표현 vs -ing형 특성 표현', 15),
('ranks', 'rank', 'verb_form', '3인칭 단수 현재형 -s', 8),
('summed', 'summing', 'verb_form', '과거형 vs 현재진행형', 10),
('to deliver', 'delivering', 'verb_form', 'to부정사 vs 동명사 선택', 6),
('increase', 'increasing', 'verb_form', '동사원형 vs 동명사', 5),
('generate', 'generating', 'verb_form', '동사원형 vs 동명사', 3),
('seen', 'saw', 'verb_form', '과거분사 vs 과거형', 4),
('broken', 'broke', 'verb_form', '과거분사 vs 과거형', 4),
('written', 'wrote', 'verb_form', '과거분사 vs 과거형', 3),
('taken', 'took', 'verb_form', '과거분사 vs 과거형', 3),
('known', 'knew', 'verb_form', '과거분사 vs 과거형', 3),
('chosen', 'chose', 'verb_form', '과거분사 vs 과거형', 2),
('frozen', 'froze', 'verb_form', '과거분사 vs 과거형', 2),
('spoken', 'spoke', 'verb_form', '과거분사 vs 과거형', 2),
('driven', 'drove', 'verb_form', '과거분사 vs 과거형', 2),

-- 2. verb_tense (시제)
('has been', 'was', 'verb_tense', '현재완료 vs 과거', 5),
('had completed', 'completed', 'verb_tense', '과거완료 vs 단순과거', 4),
('will have finished', 'will finish', 'verb_tense', '미래완료 vs 단순미래', 3),
('have lived', 'lived', 'verb_tense', '현재완료 vs 과거', 4),
('has worked', 'worked', 'verb_tense', '현재완료 vs 과거', 4),
('had left', 'left', 'verb_tense', '과거완료 vs 단순과거', 3),
('will be doing', 'will do', 'verb_tense', '미래진행 vs 단순미래', 3),
('has been studying', 'studied', 'verb_tense', '현재완료진행 vs 과거', 3),
('had been waiting', 'waited', 'verb_tense', '과거완료진행 vs 과거', 2),
('will have been working', 'will work', 'verb_tense', '미래완료진행 vs 미래', 2),

-- 3. subject_verb_agreement (수 일치)
('is', 'are', 'subject_verb_agreement', '단수 주어 + 단수 동사', 12),
('was', 'were', 'subject_verb_agreement', '단수 주어 + 단수 동사 과거', 6),
('does', 'do', 'subject_verb_agreement', '3인칭 단수 does', 5),
('has', 'have', 'subject_verb_agreement', '3인칭 단수 has', 5),
('goes', 'go', 'subject_verb_agreement', '3인칭 단수 -es', 4),
('seems', 'seem', 'subject_verb_agreement', '3인칭 단수 -s', 4),
('comes', 'come', 'subject_verb_agreement', '3인칭 단수 -s', 3),
('needs', 'need', 'subject_verb_agreement', '3인칭 단수 -s', 3),
('wants', 'want', 'subject_verb_agreement', '3인칭 단수 -s', 3),
('thinks', 'think', 'subject_verb_agreement', '3인칭 단수 -s', 3),

-- 4. relative_pronoun (관계대명사)
('which', 'that', 'relative_pronoun', '비제한적 용법 which', 7),
('who', 'which', 'relative_pronoun', '사람 선행사 who', 5),
('whose', 'which', 'relative_pronoun', '소유격 관계대명사', 4),
('whom', 'who', 'relative_pronoun', '목적격 관계대명사', 4),
('that', 'what', 'relative_pronoun', '선행사 있을 때 that', 3),
('which', 'what', 'relative_pronoun', '선행사 있을 때 which', 3),
('where', 'which', 'relative_pronoun', '장소 관계부사', 3),
('when', 'which', 'relative_pronoun', '시간 관계부사', 2),
('why', 'which', 'relative_pronoun', '이유 관계부사', 2),
('what', 'that', 'relative_pronoun', '선행사 없을 때 what', 3),

-- 5. to_infinitive_vs_gerund (to부정사 vs 동명사)
('to work', 'working', 'to_infinitive_vs_gerund', 'decide + to부정사', 5),
('working', 'to work', 'to_infinitive_vs_gerund', 'enjoy + 동명사', 5),
('to learn', 'learning', 'to_infinitive_vs_gerund', 'want + to부정사', 4),
('learning', 'to learn', 'to_infinitive_vs_gerund', 'finish + 동명사', 4),
('to go', 'going', 'to_infinitive_vs_gerund', 'plan + to부정사', 4),
('going', 'to go', 'to_infinitive_vs_gerund', 'avoid + 동명사', 4),
('to see', 'seeing', 'to_infinitive_vs_gerund', 'hope + to부정사', 3),
('seeing', 'to see', 'to_infinitive_vs_gerund', 'mind + 동명사', 3),
('to meet', 'meeting', 'to_infinitive_vs_gerund', 'expect + to부정사', 3),
('meeting', 'to meet', 'to_infinitive_vs_gerund', 'consider + 동명사', 3),

-- 6. parallel_structure (병렬구조)
('swimming, running, and cycling', 'swimming, running, and to cycle', 'parallel_structure', '병렬구조 일치', 4),
('to read, to write, and to speak', 'to read, writing, and speak', 'parallel_structure', 'to부정사 병렬', 4),
('quickly, efficiently, and accurately', 'quickly, efficient, and accurately', 'parallel_structure', '부사 병렬', 3),
('working hard and studying diligently', 'working hard and to study diligently', 'parallel_structure', '동명사 병렬', 3),
('not only smart but also hardworking', 'not only smart but also works hard', 'parallel_structure', 'not only A but also B', 3),
('either accept or reject', 'either accepting or reject', 'parallel_structure', 'either A or B', 2),
('neither beautiful nor ugly', 'neither beautiful nor ugliness', 'parallel_structure', 'neither A nor B', 2),
('both talented and dedicated', 'both talented and dedication', 'parallel_structure', 'both A and B', 2),

-- 7. modifier_position (수식어 위치)
('clearly written', 'written clearly', 'modifier_position', '과거분사 수식', 3),
('highly recommended', 'recommended highly', 'modifier_position', '과거분사 수식', 3),
('carefully planned', 'planned carefully', 'modifier_position', '과거분사 수식', 2),
('well organized', 'organized well', 'modifier_position', '과거분사 수식', 2),
('deeply moved', 'moved deeply', 'modifier_position', '과거분사 수식', 2),
('widely accepted', 'accepted widely', 'modifier_position', '과거분사 수식', 2),
('only he knows', 'he only knows', 'modifier_position', 'only 위치', 3),
('even experts', 'experts even', 'modifier_position', 'even 위치', 2),
('just a moment', 'a just moment', 'modifier_position', 'just 위치', 2),
('almost everyone', 'everyone almost', 'modifier_position', 'almost 위치', 2),

-- 8. comparative_superlative (비교급/최상급)
('more interesting', 'more interested', 'comparative_superlative', '비교급 형태', 4),
('better', 'more good', 'comparative_superlative', '불규칙 비교급', 4),
('the most important', 'the more important', 'comparative_superlative', '최상급 형태', 4),
('worse', 'more bad', 'comparative_superlative', '불규칙 비교급', 3),
('the best', 'the most good', 'comparative_superlative', '불규칙 최상급', 3),
('larger', 'more large', 'comparative_superlative', '1음절 비교급', 3),
('the biggest', 'the most big', 'comparative_superlative', '1음절 최상급', 3),
('more beautiful', 'beautifuler', 'comparative_superlative', '3음절 비교급', 3),
('the most difficult', 'the difficultest', 'comparative_superlative', '3음절 최상급', 2),
('less expensive', 'more cheap', 'comparative_superlative', 'less 비교급', 2),

-- 9. conjunction (접속사)
('Although', 'Despite', 'conjunction', 'Although + S+V vs Despite + N', 4),
('Despite', 'Although', 'conjunction', 'Despite + N vs Although + S+V', 4),
('because', 'because of', 'conjunction', 'because + S+V', 3),
('because of', 'because', 'conjunction', 'because of + N', 3),
('While', 'During', 'conjunction', 'While + S+V vs During + N', 3),
('During', 'While', 'conjunction', 'During + N vs While + S+V', 3),
('unless', 'if not', 'conjunction', 'unless = if not', 2),
('whereas', 'despite', 'conjunction', 'whereas + S+V', 2),
('since', 'for', 'conjunction', 'since + S+V (이유)', 2),
('as', 'like', 'conjunction', 'as + S+V vs like + N', 2),

-- 10. preposition (전치사)
('on Monday', 'in Monday', 'preposition', '요일 앞 on', 3),
('in the morning', 'on the morning', 'preposition', '시간대 앞 in', 3),
('at night', 'in night', 'preposition', 'at night 관용 표현', 3),
('in 2024', 'on 2024', 'preposition', '연도 앞 in', 2),
('on March 5th', 'in March 5th', 'preposition', '날짜 앞 on', 2),
('at 3 o\'clock', 'in 3 o\'clock', 'preposition', '시각 앞 at', 2),
('by car', 'with car', 'preposition', '교통수단 by', 2),
('interested in', 'interested at', 'preposition', 'be interested in', 3),
('good at', 'good in', 'preposition', 'be good at', 2),
('depend on', 'depend of', 'preposition', 'depend on', 2),

-- 11. article (관사)
('the sun', 'a sun', 'article', '유일한 것 the', 3),
('a book', 'the book', 'article', '처음 언급 a', 3),
('the book', 'book', 'article', '특정한 것 the', 3),
('an apple', 'a apple', 'article', '모음 앞 an', 2),
('a university', 'an university', 'article', '자음 발음 a', 2),
('the United States', 'United States', 'article', '국가명 the', 2),
('play the piano', 'play piano', 'article', '악기 앞 the', 2),
('go to school', 'go to the school', 'article', '목적 중시 무관사', 2),
('in the future', 'in future', 'article', 'in the future', 2),
('the most', 'most', 'article', '최상급 앞 the', 2),

-- 12. pronoun (대명사)
('themselves', 'theirselves', 'pronoun', '재귀대명사 형태', 3),
('it', 'they', 'pronoun', '단수 대명사', 3),
('their', 'his', 'pronoun', '성별 중립 their', 2),
('who', 'whom', 'pronoun', '주격 who', 2),
('whom', 'who', 'pronoun', '목적격 whom', 2),
('its', 'it\'s', 'pronoun', '소유격 its', 3),
('whose', 'who\'s', 'pronoun', '소유격 whose', 2),
('anyone', 'any one', 'pronoun', '부정대명사 anyone', 2),
('everyone', 'every one', 'pronoun', '부정대명사 everyone', 2),
('each other', 'one another', 'pronoun', '둘 사이 each other', 2),

-- 13. passive_voice (수동태)
('was built', 'built', 'passive_voice', '수동태 형태', 4),
('is being constructed', 'is constructing', 'passive_voice', '진행형 수동태', 3),
('has been completed', 'has completed', 'passive_voice', '완료형 수동태', 3),
('will be delivered', 'will deliver', 'passive_voice', '미래 수동태', 3),
('was being repaired', 'was repairing', 'passive_voice', '과거진행 수동태', 2),
('had been stolen', 'had stolen', 'passive_voice', '과거완료 수동태', 2),
('must be done', 'must do', 'passive_voice', '조동사 수동태', 3),
('should be considered', 'should consider', 'passive_voice', '조동사 수동태', 2),
('can be seen', 'can see', 'passive_voice', '조동사 수동태', 2),
('might be affected', 'might affect', 'passive_voice', '조동사 수동태', 2),

-- 14. countable_uncountable (가산/불가산)
('much information', 'many information', 'countable_uncountable', '불가산명사 much', 3),
('less money', 'fewer money', 'countable_uncountable', '불가산명사 less', 3),
('fewer people', 'less people', 'countable_uncountable', '가산명사 fewer', 3),
('many books', 'much books', 'countable_uncountable', '가산명사 many', 2),
('a piece of advice', 'an advice', 'countable_uncountable', '불가산명사 단위', 3),
('some water', 'a water', 'countable_uncountable', '불가산명사 some', 2),
('a little time', 'a few time', 'countable_uncountable', '불가산명사 a little', 2),
('a few minutes', 'a little minutes', 'countable_uncountable', '가산명사 a few', 2),
('equipment', 'equipments', 'countable_uncountable', '불가산명사 복수 없음', 2),
('furniture', 'furnitures', 'countable_uncountable', '불가산명사 복수 없음', 2),

-- 15. conditional (조건문)
('If I were', 'If I was', 'conditional', '가정법 과거 were', 4),
('would have gone', 'would go', 'conditional', '가정법 과거완료', 3),
('had known', 'knew', 'conditional', '가정법 과거완료 조건절', 3),
('will help', 'would help', 'conditional', '직설법 미래', 2),
('would be', 'will be', 'conditional', '가정법 과거', 2),
('could have done', 'could do', 'conditional', '가정법 과거완료', 2),
('should have studied', 'should study', 'conditional', '과거 후회', 2),
('If it rains', 'If it will rain', 'conditional', '조건절 현재', 3),
('unless it rains', 'unless it will rain', 'conditional', 'unless 조건절', 2),
('provided that', 'providing', 'conditional', 'provided that + S+V', 2),

-- 16. word_order (어순)
('rarely do I', 'rarely I do', 'word_order', '부정부사 도치', 3),
('never have I', 'never I have', 'word_order', '부정부사 도치', 3),
('so am I', 'so I am', 'word_order', 'so 도치', 2),
('neither can I', 'neither I can', 'word_order', 'neither 도치', 2),
('Only then did', 'Only then', 'word_order', 'only 부사구 도치', 2),
('Not only is', 'Not only', 'word_order', 'not only 도치', 2),
('Hardly had', 'Hardly', 'word_order', 'hardly 도치', 2),
('Seldom does', 'Seldom', 'word_order', 'seldom 도치', 2),
('Little did', 'Little', 'word_order', 'little 도치', 1),
('No sooner had', 'No sooner', 'word_order', 'no sooner 도치', 1),

-- 17. other (기타)
('delicate', 'delicately', 'other', '형용사 vs 부사', 2),
('different from', 'different than', 'other', 'different from 관용', 2),
('similar to', 'similar with', 'other', 'similar to 관용', 2),
('succeed in', 'succeed to', 'other', 'succeed in 관용', 2),
('capable of', 'capable to', 'other', 'capable of 관용', 2),
('prevent from', 'prevent to', 'other', 'prevent from 관용', 2),
('apologize for', 'apologize of', 'other', 'apologize for 관용', 2),
('congratulate on', 'congratulate for', 'other', 'congratulate on 관용', 1),
('insist on', 'insist in', 'other', 'insist on 관용', 1),
('consist of', 'consist in', 'other', 'consist of 관용', 1),

-- 추가 고빈도 패턴들 (50개 더)
('seems to be', 'seems to', 'verb_form', 'seem to be 구조', 3),
('appears to have', 'appears to', 'verb_form', 'appear to have 구조', 2),
('tends to increase', 'tends increasing', 'to_infinitive_vs_gerund', 'tend + to부정사', 2),
('used to live', 'used living', 'to_infinitive_vs_gerund', 'used to 과거습관', 3),
('be used to living', 'be used to live', 'to_infinitive_vs_gerund', 'be used to + 동명사', 3),
('look forward to seeing', 'look forward to see', 'to_infinitive_vs_gerund', 'look forward to + 동명사', 3),
('object to doing', 'object to do', 'to_infinitive_vs_gerund', 'object to + 동명사', 2),
('contribute to solving', 'contribute to solve', 'to_infinitive_vs_gerund', 'contribute to + 동명사', 2),
('devote to helping', 'devote to help', 'to_infinitive_vs_gerund', 'devote to + 동명사', 2),
('commit to working', 'commit to work', 'to_infinitive_vs_gerund', 'commit to + 동명사', 2),

('have difficulty doing', 'have difficulty to do', 'to_infinitive_vs_gerund', 'have difficulty + 동명사', 2),
('spend time doing', 'spend time to do', 'to_infinitive_vs_gerund', 'spend time + 동명사', 3),
('be worth reading', 'be worth to read', 'to_infinitive_vs_gerund', 'be worth + 동명사', 2),
('cannot help laughing', 'cannot help to laugh', 'to_infinitive_vs_gerund', 'cannot help + 동명사', 2),
('feel like going', 'feel like to go', 'to_infinitive_vs_gerund', 'feel like + 동명사', 2),

('make him do', 'make him to do', 'verb_form', '사역동사 make + 원형', 3),
('let her go', 'let her to go', 'verb_form', '사역동사 let + 원형', 3),
('have them clean', 'have them to clean', 'verb_form', '사역동사 have + 원형', 2),
('help us (to) understand', 'help us understanding', 'verb_form', 'help + (to)원형', 2),
('see him leave', 'see him to leave', 'verb_form', '지각동사 + 원형', 3),
('watch them play', 'watch them to play', 'verb_form', '지각동사 + 원형', 2),
('hear her sing', 'hear her to sing', 'verb_form', '지각동사 + 원형', 2),
('notice it move', 'notice it to move', 'verb_form', '지각동사 + 원형', 2),

('it is important to', 'it is important that', 'conjunction', 'it is adj + to부정사', 2),
('so that he can', 'so that he could', 'conjunction', 'so that 목적', 2),
('in order to succeed', 'in order that succeed', 'conjunction', 'in order to + 동사원형', 2),
('whether to go', 'whether go', 'conjunction', 'whether to 간접의문', 2),

('the number of students', 'a number of students', 'subject_verb_agreement', 'the number 단수', 3),
('a number of students', 'the number of students', 'subject_verb_agreement', 'a number 복수', 3),
('one of the boys', 'one of the boy', 'countable_uncountable', 'one of + 복수', 2),
('each of them', 'each of they', 'pronoun', 'each of + 목적격', 2),
('every student has', 'every student have', 'subject_verb_agreement', 'every 단수', 2),
('each student needs', 'each student need', 'subject_verb_agreement', 'each 단수', 2),

('what is called', 'that is called', 'relative_pronoun', '선행사 포함 what', 2),
('what matters most', 'that matters most', 'relative_pronoun', '명사절 what', 2),
('the reason why', 'the reason because', 'relative_pronoun', 'the reason why', 2),
('the way how', 'the way', 'relative_pronoun', 'the way (how 생략)', 2),
('the time when', 'the time which', 'relative_pronoun', '시간 when', 2),
('the place where', 'the place which', 'relative_pronoun', '장소 where', 2),

('not A but B', 'not A and B', 'conjunction', 'not A but B', 2),
('as well as', 'and', 'conjunction', 'as well as', 2),
('rather than', 'than', 'conjunction', 'rather than', 2),
('other than', 'except', 'preposition', 'other than', 1),
('apart from', 'except', 'preposition', 'apart from', 1),
('aside from', 'except', 'preposition', 'aside from', 1),
('regardless of', 'regardless', 'preposition', 'regardless of + N', 2),
('in spite of', 'in spite', 'preposition', 'in spite of + N', 2),
('instead of', 'instead', 'preposition', 'instead of + N', 2),
('according to', 'according', 'preposition', 'according to + N', 2);
