export const getEnglishDefinitionBlankMatchPrompt = (text: string): string => {
  const BLANK = "__________";
  const lines: string[] = [];
  lines.push('당신은 영어 교사입니다. 주어진 영어 지문을 바탕으로 "빈칸-영영풀이 매칭" 객관식 문제를 만들어주세요.');
  lines.push("");
  lines.push("[문제 형식]");
  lines.push("- 지문에서 핵심 동사(또는 동사구) 5개를 골라 각각 (A), (B), (C), (D), (E)로 표시하고 해당 위치를 빈칸 처리합니다.");
  lines.push(`- 빈칸은 모두 "${BLANK}" (밑줄 10개) 형태로 통일합니다. 예: (A)${BLANK}`);
  lines.push("- 그 다음 <영영 풀이> 박스에 영영 정의 6개(ⓐ~ⓕ)를 제시합니다. 5개는 (A)~(E)의 정답이고, 1개는 오답(distractor)입니다.");
  lines.push('- 5개의 객관식 선택지(①~⑤)는 "(라벨)-(원문자), (라벨)-(원문자)" 형식의 2쌍짜리 매칭으로 구성합니다. 정답 보기는 두 쌍 모두 올바른 매칭이어야 하고, 오답 4개는 적어도 한 쌍이 틀려야 합니다.');
  lines.push("- 정답은 ①~⑤ 중 무작위 위치에 배치하세요(① 편중 금지). 매번 다른 위치에 배치하도록 분포시키세요.");
  lines.push("");
  lines.push("[영영풀이 작성 규칙]");
  lines.push('- 모든 정의는 학습용 영영사전 스타일("to ..." 형식) — 5~12 단어 길이로 통일');
  lines.push("- 빈칸에 들어갈 단어 자체를 정의 안에 직접 노출하지 말 것");
  lines.push("- 오답(distractor) 정의는 그럴듯하지만 지문 내 어떤 빈칸에도 맞지 않아야 함");
  lines.push("");
  lines.push("[CRITICAL — 원문 보존]");
  lines.push("- 빈칸 처리한 5개 단어/구문을 제외하고는 원문의 모든 단어를 정확히 그대로 유지하세요. 추가/삭제/변경 금지.");
  lines.push("");
  lines.push("[출력 형식 — 아래 형식을 그대로 따르세요. <box> 태그도 그대로 출력하세요. <box> 외 다른 추가 설명/머리말 금지.]");
  lines.push("");
  lines.push("다음 문장의 빈칸 (A)~(E)에 들어갈 말의 영영풀이가 알맞게 짝지어진 것은?");
  lines.push("<box>");
  lines.push(`[빈칸 (A)~(E)가 포함된 영어 지문 전체. 원문 그대로 유지하되 5개 위치만 (A)${BLANK} 형태로 치환]`);
  lines.push("</box>");
  lines.push("<box>");
  lines.push("ⓐ to ...");
  lines.push("ⓑ to ...");
  lines.push("ⓒ to ...");
  lines.push("ⓓ to ...");
  lines.push("ⓔ to ...");
  lines.push("ⓕ to ...");
  lines.push("</box>");
  lines.push("");
  lines.push("① (A)-ⓒ, (E)-ⓓ");
  lines.push("② (A)-ⓐ, (C)-ⓑ");
  lines.push("③ (B)-ⓕ, (D)-ⓔ");
  lines.push("④ (C)-ⓓ, (D)-ⓕ");
  lines.push("⑤ (B)-ⓔ, (D)-ⓐ");
  lines.push("[정답] [번호]");
  lines.push("[해설] 각 빈칸의 정답 단어와 매칭되는 영영풀이를 간단히 설명하세요.");
  lines.push("");
  lines.push("[원문 지문]");
  lines.push(text);
  return lines.join("\n");
};
