// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Export these constants for use in other parts of the app
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missing = [
    !SUPABASE_URL && 'VITE_SUPABASE_URL',
    !SUPABASE_PUBLISHABLE_KEY && 'VITE_SUPABASE_PUBLISHABLE_KEY',
  ]
    .filter(Boolean)
    .join(', ');
  const message = `[supabase] Missing environment variable(s): ${missing}. Copy .env.example to .env and fill in the values.`;
  console.error(message);
  throw new Error(message);
}

// Kept for modules that build edge-function URLs by hand; values now come from .env
export const SUPABASE_PUBLIC_URL = SUPABASE_URL;
export const SUPABASE_PUBLIC_KEY = SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_PUBLIC_URL, 
  SUPABASE_PUBLIC_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        apikey: SUPABASE_PUBLIC_KEY,
        Authorization: `Bearer ${SUPABASE_PUBLIC_KEY}`,
        'x-client-info': 'veritas-app',
        'Content-Type': 'application/json',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'
      }
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);

// Helper function to create a direct API fetch with proper headers and cache control
export const createDirectApiRequest = async (
  endpoint: string, 
  method: 'GET' | 'POST' | 'DELETE' | 'PATCH' = 'GET', 
  body?: any
) => {
  // Ensure endpoint is clean (avoid query parameters with caches or timestamps)
  const cleanEndpoint = endpoint.includes('?') 
    ? endpoint 
    : `${endpoint}`;
  
  const url = `${SUPABASE_PUBLIC_URL}${cleanEndpoint}`;
  
  // Add timestamp to prevent caching
  const timestamp = new Date().getTime();
  
  const headers = {
    'Authorization': `Bearer ${SUPABASE_PUBLIC_KEY}`,
    'apikey': SUPABASE_PUBLIC_KEY,
    'Content-Type': 'application/json',
    'Cache-Control': 'no-cache, no-store, must-revalidate',
    'Pragma': 'no-cache',
    'Expires': '0',
    'x-custom-timestamp': `${timestamp}`
  };
  
  const requestOptions: RequestInit = {
    method,
    headers,
    cache: 'no-store',
  };
  
  if (body && (method === 'POST' || method === 'PATCH')) {
    requestOptions.body = JSON.stringify(body);
  }
  
  try {
    console.log(`Making ${method} request to ${url}`);
    const response = await fetch(url, requestOptions);
    
    if (!response.ok) {
      const errorText = await response.text();
      console.error(`API request failed: ${response.status} ${response.statusText}`, errorText);
      throw new Error(`API request failed: ${response.status} ${response.statusText}`);
    }
    
    return response;
  } catch (error) {
    console.error('Error in API request:', error);
    throw error;
  }
};
