// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missing = [
    !SUPABASE_URL && 'VITE_SUPABASE_URL',
    !SUPABASE_PUBLISHABLE_KEY && 'VITE_SUPABASE_PUBLISHABLE_KEY',
  ]
    .filter(Boolean)
    .join(', ');
  const message = `[supabase] Missing environment variable(s): ${missing}. Copy .env.example to .env and fill in the values.`;
  console.error(message);
  throw new Error(message);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to recursively delete related records
export const deleteClassWithRelatedData = async (classId: string) => {
  try {
    // Delete test_schedules related to the class
    const { error: testSchedulesError } = await supabase
      .from('test_schedules')
      .delete()
      .eq('class_id', classId);
    
    if (testSchedulesError) throw testSchedulesError;

    // Delete curriculum_calendar entries for the class
    const { error: calendarError } = await supabase
      .from('curriculum_calendar')
      .delete()
      .eq('class_id', classId);
    
    if (calendarError) throw calendarError;

    // Delete manual_classes entries for the class
    const { error: manualClassesError } = await supabase
      .from('manual_classes')
      .delete()
      .eq('class_id', classId);
    
    if (manualClassesError) throw manualClassesError;

    // Delete progress_records for the class
    const { error: progressRecordsError } = await supabase
      .from('progress_records')
      .delete()
      .eq('class_id', classId);
    
    if (progressRecordsError) throw progressRecordsError;

    // Delete students in the class
    const { error: studentsError } = await supabase
      .from('students')
      .delete()
      .eq('class_id', classId);
    
    if (studentsError) throw studentsError;

    // Finally, delete the class itself
    const { error: classError } = await supabase
      .from('classes')
      .delete()
      .eq('id', classId);
    
    if (classError) throw classError;

    return { success: true };
  } catch (error) {
    console.error('Error deleting class with related data:', error);
    return { success: false, error };
  }
};
