/* 레슨 조각 하나를 규격에 맞는지 검사한다.  node lcheck.js units/_l01.js */
const CIR = "①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⑱⑲⑳".split("");
const t = require(process.argv[2].startsWith("/") ? process.argv[2] : "./" + process.argv[2]);
let bad = 0; const err = m => { bad++; console.log("  " + m); };
const n = (t.sent || []).length;
if (!n) err("sent 가 없다");
if ((t.kor || []).length !== n) err(`지문 ${n}문장 ≠ 해석 ${(t.kor||[]).length}줄`);
const words = t.sent.join(" ").split(/\s+/).length;
if (words < 165 || words > 340) err(`지문 ${words} 단어 (165–340)`);
["no","key","accent","tint","deep","en","ko","goal","fig","tip"].forEach(k => { if (!t[k]) err(`${k} 없음`); });
if (t.bank.length !== 6) err(`bank ${t.bank.length}개`);
if (t.defs.length !== 6) err(`defs ${t.defs.length}개`);
if (t.bank.some((b,i) => b[0] !== t.defs[i][0])) err("bank 와 defs 의 낱말·순서가 다르다");
t.defs.forEach(d => { if (d[1].length > 60) err(`영영풀이 60자 초과: ${d[1]}`); });
if ([...t.defOrder].sort((a,b)=>a-b).join() !== "0,1,2,3,4,5") err(`defOrder 순열 아님: ${t.defOrder}`);
t.bank.forEach(b => { if (CIR.indexOf(b[1]) >= n) err(`bank 문장번호 ${b[1]} 범위 밖`); });
t.bank.forEach(b => { const w=b[0].replace(/e?s$|ed$|ing$/,""); if (!t.sent.join(" ").toLowerCase().includes(w.toLowerCase().slice(0,Math.max(4,w.length-2)))) err(`bank 낱말이 지문에 없다: ${b[0]}`); });
if (CIR.indexOf(t.fl.model.n) >= n) err(`먼저 보기 번호 ${t.fl.model.n} 범위 밖`);
if (t.fl.model.toks.map(x=>x[0]).join(" ") !== t.sent[CIR.indexOf(t.fl.model.n)])
  err(`먼저 보기 토큰을 이으면 원문과 다르다\n      토큰: ${t.fl.model.toks.map(x=>x[0]).join(" ")}\n      원문: ${t.sent[CIR.indexOf(t.fl.model.n)]}`);
if (t.fl.drill.length !== 3) err(`drill ${t.fl.drill.length}개`);
t.fl.drill.forEach(d => { const i = CIR.indexOf(d.n);
  if (i < 0 || i >= n) return err(`drill 번호 ${d.n} 범위 밖`);
  if (t.sent[i] !== d.en) err(`drill ${d.n} 문장이 지문과 다름\n      drill: ${d.en}\n      원문 : ${t.sent[i]}`);
  if (d.n === t.fl.model.n) err(`drill ${d.n} 이 먼저 보기와 겹친다`); });
if (t.syn.length !== 2) err(`syn ${t.syn.length}개`);
t.syn.forEach(x => { if (CIR.indexOf(x.n) >= n) err(`syn 번호 ${x.n} 범위 밖`); });
if (t.synd.map(d=>d.u).join("|") !== "구문 1|구문 2|구문 1 + 2") err("synd 구성이 규격과 다르다");
if (t.flow.length !== 5) err(`flow ${t.flow.length}행`);
const fa = t.flow.filter(r=>r[2]).map(r=>r[2]);
if (fa.length !== 4) err(`flow 빈칸 ${fa.length}개 (4개)`);
const fb = t.flowBogi.split("·").map(s=>s.trim());
if (fb.length !== 6) err(`flowBogi ${fb.length}개 (6개)`);
fa.forEach(a => { if (!fb.includes(a)) err(`flow 정답 "${a}" 가 보기에 없다`); });
t.flow.forEach(r => { if (r[2] && !/\(\s*[①-⑳]\s*\)/.test(r[1])) err(`flow 행에 빈칸 표시 없음: ${r[0]}`); });
if (t.para.length !== 5) err(`para ${t.para.length}개`);
const pb = t.paraBogi.split("·").map(s=>s.trim());
if (pb.length !== 8) err(`paraBogi ${pb.length}개 (8개)`);
t.para.forEach(p => { const m = p[0].match(/^([①-⑳])\s/);
  if (!m) return err(`para 앞에 문장 번호 없음: ${p[0].slice(0,26)}`);
  if (CIR.indexOf(m[1]) >= n) err(`para 번호 ${m[1]} 범위 밖`);
  if (p[0].replace(/^[①-⑳]\s/,"").length > 52) err(`para 원문 52자 초과: ${p[0]}`);
  if (p[1].length > 56) err(`para 문장 56자 초과: ${p[1]}`);
  if (!p[1].includes("______")) err(`para 문장에 빈칸 없음: ${p[1]}`);
  if (!pb.includes(p[2])) err(`para 정답 "${p[2]}" 가 보기에 없다`);
  const filled = p[1].replace("______", p[2]);
  if (filled.length > 52) err(`para 정답 채운 문장 52자 초과 (${filled.length}자): ${filled}`); });
if (t.check.length !== 3) err(`check ${t.check.length}개`);
[0,1].forEach(i => { if (t.check[i].ch.length !== 5) err(`check${i+1} 선지 ${t.check[i].ch.length}개`);
  if (!(t.check[i].ans>=1 && t.check[i].ans<=5)) err(`check${i+1} 정답 번호 이상`); });
["wtype","stype","why","src"].forEach(k => { if (t[k].length !== 5) err(`${k} ${t[k].length}개`); });
if (t.wtype[t.check[0].ans-1] !== "정답") err("wtype 의 정답 위치가 check1 정답과 어긋남");
if (t.why[t.check[0].ans-1][0] !== "정답") err("why 의 정답 위치가 어긋남");
if (t.stype[t.check[1].ans-1] === "일치") err("stype: 정답 선지가 '일치'");
t.stype.forEach((s,i) => { if (i !== t.check[1].ans-1 && s !== "일치") err(`stype ${CIR[i]} 는 '일치'여야 함`); });
if (t.kb.items.length !== 3) err(`kb 항목 ${t.kb.items.length}개`);
if (!t.kb.ask) err("kb 에 '생각해 볼 것'이 없다");
console.log(bad ? `── 문제 ${bad}건` : `── 레슨 ${t.no} 규격 통과 (${n}문장 ${words}단어)`);
process.exit(bad ? 1 : 0);
