/* Unit 1 READ RIGHT 표기 */
module.exports = {
 "01": [
  [["There",null],["is","v"],["special difficulty","s"],["in a universalized study of literature.","m"]],
  [["Although","c"],["literature","s2"],["contains","v2"],["universal human spirits and sentiments,",null],["a universal language","s"],["— written or spoken —","m"],["is","v"],["still lacking.",null]],
  [["Each country","s"],["creates","v"],["its literature",null],["with its own language.","m"]],
  [["In such circumstances,","m"],["how","m"],["could","v"],["a universalized study of literature","s"],["be","v"],["possible?",null]],
  [["No one","s"],["knows","v"],["everything;",null],["no one","s"],["can learn","v"],["every language,",null],["and","c"],["be able to read and study","v"],["literatures",null],["from all over the world.","m"]],
  [["Needless to say,","m"],["it","s"],["is","v"],["absolutely impossible",null],["for laymen","m"],["to understand all the world's literatures.",null]],
  [["They","s"],["can understand","v"],["nothing other than their own language.",null]],
  [["How,","m"],["then,","m"],["could","v"],["a universalized study of literature","s"],["be","v"],["possible?",null]],
  [["It","s"],["is","v"],["true",null],["that","c"],["scholars and even common readers","s2"],["can use","v2"],["translations,",null],["but","c"],["how faithful",null],["is","v"],["a translation","s"],["to the original?","m"]],
  [["The value and enjoyment of the original","s"],["may be lost","v"],["through translation.","m"]],
  [["In the end,","m"],["how","m"],["can","v"],["literature","s"],["be translated?","v"]],
  [["Literature","s"],["is","v"],["the manifestation of the author's emotions and inspirations.",null]],
  [["At the moment of emotional intensity or epiphany,","m"],["the work","s"],["naturally","m"],["flows","v"],["under the author's hand.","m"]],
  [["Once","c"],["the moment","s2"],["passes,","v2"],["the natural flowing of writing","s"],["can never be repeated,","v"],["let alone","c"],["reproduced through translation in someone else's hand.",null]],
  [["What is more,","m"],["literature","s"],["almost always","m"],["has","v"],["a local color.",null]],
  [["Such color","s"],["is","v"],["most vivid and lively",null],["in the eyes of the local people,","m"],["but","c"],["means","v"],["nothing",null],["to others.","m"]],
  [["A deliberate representation","s"],["is","v"],["a concession",null],["after all.","m"]],
  [["Also,","m"],["moods, imaginations, and even thoughts","s"],["in literature","m"],["are so closely related","v"],["to words","m"],["that","c"],["once","c"],["the latter","s2"],["change,","v2"],["the former","s2"],["change","v2"],["as well.","m"]]
 ],
 "02": [
  [["There",null],["is","v"],["a curious cliché","s"],["that","c"],["says","v2"],["pictures don't lie.",null]],
  [["This","s"],["is","v"],["part of that greater cliché",null],["that","c"],["says","v2"],["seeing is believing.",null]],
  [["Somehow","m"],["a thing","s"],["seen directly — or through a visual representation like a painting, a photograph, or a film —","m"],["makes","v"],["us feel closer to some actual reality.",null]],
  [["Words","s"],["are too obviously not","v"],["things themselves;",null],["words","s"],["are","v"],["made-up sounds,",null],["developed throughout the life of a culture,","m"],["represented by made-up letters,","m"],["put together in a contrived grammar","m"],["that","c"],["everyone in a culture","s2"],["uses","v2"],["to communicate","m"],["through a decision","m"],["that","c"],["particular words in a particular order","s2"],["will refer","v2"],["to particular things.","m"]],
  [["Language","s"],["is","v"],["clearly cultural and not natural:",null],["it","s"],["is","v"],["human-made and accepted",null],["with some variations throughout a particular culture.","m"]],
  [["Every English speaker","s"],["understands","v"],["what the word “food” refers to,",null],["even though","c"],["the particular kind of food","s2"],["that comes to mind to each individual","m"],["will vary.","v2"]],
  [["More abstract words,","s"],["like “cool” or “sick,”","m"],["may have","v"],["a range of meanings",null],["that","c"],["keep","v2"],["changing.",null]],
  [["But","c"],["seeing the image of a thing","s"],["seems","v"],["to bring us very close to the thing itself",null],["— to “reality.”","m"]],
  [["Things","s"],["that","c"],["are seen","v2"],["appear","v"],["to be and even feel",null],["as if","c"],["they","s2"],["are unmediated;","v2"],["that is,","m"],["they","s"],["seem","v"],["to be conveyed directly to us,",null],["not conveyed indirectly.","m"]],
  [["Nothing","s"],["stands","v"],["in their way.","m"]],
  [["They","s"],["are","v"],["true.",null]],
  [["But,","c"],["in fact,","m"],["an image,","s"],["whether photographed, painted, or digitized,","m"],["is not","v"],["the thing itself.",null]],
  [["This","s"],["is","v"],["something",null],["humorously recognized by the Belgian surrealist painter, Rene Magritte,","m"],["in his painting of a pipe.","m"]],
  [["The painting","s"],["is called","v"],["The Treachery of Images",null],["and","c"],["bears","v"],["the words (in French), “Ceci n'est pas une pipe,” “This Is Not a Pipe.”",null]]
 ],
 "03": [
  [["Concert pianists","s"],["spend","v"],["much more of their lifetimes",null],["practising","m"],["than","c"],["they","s2"],["do","v2"],["playing concerts.",null]],
  [["It's","v"],["not just","m"],["that","c"],["pieces","s2"],["need","v2"],["to be kept in the memory",null],["— muscle and mind —","m"],["but","c"],["the very act of playing the piano","s"],["is","v"],["physical and athletic.",null]],
  [["It","s"],["involves","v"],["reflex and endurance.",null]],
  [["It","s"],["might be","v"],["true",null],["that","c"],["you","s2"],["never forget","v2"],["how to ride a bicycle,",null],["but","c"],["if","c"],["you and it","s2"],["are","v2"],["rusty,",null],["there's","v"],["not much hope of winning or even completing the Tour de France.",null]],
  [["So","c"],["we","s"],["need","v"],["to practise.",null]],
  [["The key","s"],["is","v"],["how","c"],["we","s2"],["make","v2"],["our time offstage",null],["best serve our briefer time onstage.",null]],
  [["A pianist","s"],["who","c"],["has","v2"],["concerts",null],["has","v"],["little time to spare,",null],["so","c"],["it's","v"],["important",null],["that","c"],["those spare hours, even minutes,","s2"],["be used","v2"],["well.","m"]],
  [["My teacher,","s"],["Gordon Green,","m"],["used to say,","v"],["‘In practice a perfectionist, in performance a realist.’",null]],
  [["In other words,","m"],["prepare","v"],["assiduously, tirelessly, at home,","m"],["but","c"],["when onstage","m"],["accept","v"],["the situation at hand",null],["without wishing","m"],["the piano","s2"],["were","v2"],["more in tune,",null],["the audience","s2"],["were","v2"],["more appreciative (or larger),",null],["you","s2"],["hadn't made","v2"],["a mess of that octave passage,",null],["and so on.","m"]],
  [["Being a ‘realist’","s"],["sounds","v"],["rather prosaic",null],["when faced with bringing to poetic, passionate life","m"],["the masterworks of master composers.",null]],
  [["I","s"],["might put","v"],["it",null],["differently from Gordon:","m"],["in practice an engineer, in performance a pilot.",null]],
  [["Nuts and bolts in a plane","s"],["are","v"],["incomparably important,",null],["but","c"],["when","c"],["you","s2"],["sit","v2"],["at the cockpit of a Steinway concert grand,","m"],["your eyes","s"],["need to look","v"],["ahead not underneath.","m"]],
  [["The purpose of practising","s"],["is","v"],["so that","c"],["we","s2"],["(offstage as engineers)","m"],["make sure","v2"],["that","c"],["we","s2"],["(onstage as pilots)","m"],["are","v2"],["completely free to fly to the destination of our choice.",null]],
  [["That destination","s"],["is","v"],["one",null],["involving imagination, creativity, and spirituality,","m"],["not merely the A to B of playing the notes",null],["— but","c"],["without the nuts and bolts in place,","m"],["we","s"],["shall never be","v"],["airborne.",null]]
 ],
 "04": [
  [["In the Disney movie Sleeping Beauty,","m"],["the King and Queen","s"],["have","v"],["a daughter,",null],["the princess Aurora,","m"],["after a long wait.","m"]],
  [["They","s"],["plan","v"],["a great christening",null],["to introduce her to the world.","m"]],
  [["They","s"],["welcome","v"],["everyone",null],["who","c"],["loves and honours","v2"],["their new daughter.",null]],
  [["But","c"],["they","s"],["fail","v"],["to invite Maleficent,",null],["who","c"],["appears","v2"],["in her negative guise as the Queen of the Underworld.","m"]],
  [["This","s"],["means,","v"],["symbolically,","m"],["that","c"],["the two monarchs","s2"],["are overprotecting","v2"],["their beloved daughter",null],["by setting up a world around her","m"],["that","c"],["has","v2"],["nothing negative",null],["in it.","m"]],
  [["But","c"],["this","s"],["does not protect","v"],["her.",null]],
  [["It","s"],["makes","v"],["her weak.",null]],
  [["Maleficent","s"],["curses","v"],["the princess,",null],["sentencing her to death at the age of sixteen,","m"],["caused by the prick of a spinning wheel's needle.","m"]],
  [["Fortunately,","m"],["a good fairy","s"],["reduces","v"],["the punishment",null],["to unconsciousness,","m"],["which","c"],["can be undone","v2"],["with love's first kiss.","m"]],
  [["The panicked King and Queen","s"],["get rid of","v"],["all the spinning wheels",null],["in the land,","m"],["and","c"],["turn","v"],["their daughter",null],["over to the three good fairies.","m"]],
  [["They","s"],["continue","v"],["with their strategy of removing all dangerous things,","m"],["but","c"],["in doing so","m"],["they","s2"],["leave","v2"],["their daughter",null],["naive, immature and weak.",null]],
  [["One day,","m"],["just before Aurora's sixteenth birthday,","m"],["she","s"],["meets","v"],["a prince",null],["in the forest","m"],["and","c"],["falls","v"],["in love.","m"]],
  [["Then","m"],["she","s"],["loudly","m"],["bemoans","v"],["the fact",null],["that","c"],["she","s2"],["is to be wed","v2"],["to Prince Philip,","m"],["whom","c"],["she","s2"],["was promised to","v2"],["as a child,","m"],["and","c"],["collapses","v"],["emotionally","m"],["when","c"],["she","s2"],["is brought back","v2"],["to her parents' castle for her birthday.","m"]],
  [["It","s"],["is","v"],["at that moment","m"],["that","c"],["Maleficent's curse","s2"],["manifests","v2"],["itself.",null]],
  [["A portal","s"],["opens up","v"],["in the castle,","m"],["a spinning wheel","s"],["appears,","v"],["and","c"],["Aurora","s"],["pricks","v"],["her finger",null],["and","c"],["falls","v"],["unconscious.",null]],
  [["She","s"],["becomes","v"],["Sleeping Beauty.",null]],
  [["Ultimately,","m"],["through true love's kiss,","m"],["Aurora","s"],["awakens","v"],["from the curse","m"],["and","c"],["begins","v"],["to grow into a mature princess,",null],["no longer just a sheltered figure but someone ready to take charge of her own life.",null]]
 ],
 "05": [
  [["Literary study,","s"],["like all disciplines,","m"],["has developed","v"],["its own terminology and its own techniques.",null]],
  [["Some knowledge and understanding of both","s"],["can greatly enhance","v"],["our personal appreciation of literature and our conversations with others about it.",null]],
  [["Literature","s"],["also has","v"],["a context and a history,",null],["and","c"],["learning something about them","s2"],["can make","v2"],["all the difference",null],["in the amount and kind of pleasure and insight","m"],["you derive from literature.",null]],
  [["By reading and discussing different genres of literature,","m"],["as well as works from varied times and places,","m"],["you","s"],["may well come","v"],["to appreciate and even love works",null],["that","c"],["you","s2"],["might never have discovered or chosen","v2"],["to read on your own",null],["or","c"],["that","c"],["you","s2"],["might have disliked or misunderstood","v2"],["if","c"],["you","s2"],["had read","v2"],["them alone.",null]],
  [["Most important,","m"],["writing about works of literature and discussing them with teachers and other students","s"],["will give","v"],["you practice",null],["in analyzing literature in greater depth","m"],["and","c"],["in considering alternative views of both the works themselves and the situations and problems","m"],["the works","s2"],["explore.","v2"]],
  [["A clear understanding of the aims and designs of a story, poem, or play","s"],["never falls","v"],["like a bolt from the blue.","m"]],
  [["Instead,","m"],["it","s"],["emerges","v"],["from a process","m"],["that","c"],["involves","v2"],["trying to put into words how and why this work had such an effect on you",null],["and,","c"],["just as important,","m"],["responding to what others say or write about it.",null]],
  [["Literature itself","s"],["is","v"],["a vast, ongoing, ever-evolving conversation",null],["in which","c"],["we","s2"],["most fully","m"],["participate","v2"],["when","c"],["we","s2"],["enter","v2"],["into actual conversation with others.","m"]]
 ]
};
