/* Unit 3 READ RIGHT 표기 */
module.exports = {
 "11": [
  [["The reality of economic relationships","s"],["can be","v"],["highly complex",null],["and","c"],["may not even be","v"],["fully observable,",null],["and","c"],["it","s"],["may even be","v"],["impossible to estimate using the observed data.",null]],
  [["Hence,","m"],["economists","s"],["build","v"],["a model — a simplified version of reality —",null],["that","c"],["is","v2"],["simple enough to be mathematically and statistically tractable.",null]],
  [["The model","s"],["enables","v"],["economists to estimate the simplified relationship",null],["using the data,","m"],["which","c"],["sheds","v2"],["light on the reality of the relationship.",null]],
  [["The model","s"],["can be regarded","v"],["as an approximation of reality,","m"],["and","c"],["it","s"],["is","v"],["the hope of the economists",null],["that","c"],["their model","s2"],["is","v2"],["a good approximation of the true relationship.",null]],
  [["As","c"],["the famous statistician George Box","s2"],["stated","v2"],["in 1976,","m"],["“all models","s"],["are","v"],["wrong,",null],["but","c"],["some","s"],["are","v"],["useful.”",null]],
  [["The statement","s"],["means","v"],["the model is an approximation,",null],["which","c"],["can sometimes be","v2"],["a good representation of reality.",null]],
  [["In this case,","m"],["the model","s"],["can provide","v"],["useful results",null],["about the relationship.","m"]],
  [["However,","m"],["often","m"],["the model","s"],["represents","v"],["a poor approximation",null],["and","c"],["may provide","v"],["misleading conclusions",null],["about the relationship.","m"]],
  [["In their training,","m"],["economists","s"],["learn","v"],["how to employ various statistical methods",null],["to find a model","m"],["that","c"],["is","v2"],["a good approximation of reality.",null]],
  [["This discipline","s"],["is called","v"],["econometrics,",null],["which","c"],["involves","v2"],["statistical and mathematical approaches to modeling economic relationships.",null]],
  [["A useful model","s"],["is","v"],["hard to get,",null],["but","c"],["it","s"],["provides","v"],["interesting information",null],["from data","m"],["and","c"],["can be used","v"],["by economists","m"],["to make important predictions and policy decisions.","m"]]
 ],
 "12": [
  [["It","s"],["is","v"],["thanks to the technology involved in Web 2.0",null],["that","c"],["people","s2"],["may now actively engage","v2"],["with internet content.","m"]],
  [["If","c"],["at first","m"],["we","s2"],["had to make do","v2"],["with witty PowerPoint attachments,","m"],["now","m"],["we","s"],["can create and upload","v"],["our own clips, gifs, selfies, etc.",null]],
  [["For example,","m"],["YouTube","s"],["hosts","v"],["countless videos",null],["uploaded by members of the public.","m"]],
  [["Anyone","s"],["can produce and post","v"],["a homemade video",null],["on YouTube,","m"],["just as","c"],["they","s2"],["may post","v2"],["a scene they themselves have extracted from a professionally made film or a TV series",null],["or","c"],["even create","v2"],["a compilation of different scenes by a certain actor or on a particular topic.",null]],
  [["And","c"],["much of what people upload on YouTube","s"],["appears","v"],["to be actually humorous in intent.",null]],
  [["Of course,","m"],["these compilations","s"],["beg","v"],["a number of questions.",null]],
  [["They","s"],["are not only divorced","v"],["from the contexts","m"],["in which","c"],["they","s2"],["first appeared,","v2"],["but","c"],["they","s"],["are consumed","v"],["in a different era,","m"],["and","c"],["this","s"],["must surely have","v"],["an effect on the way they are received.",null]],
  [["Similarly,","m"],["Facebook","s"],["also allows","v"],["users to upload and share things with others,",null],["and","c"],["undoubtedly here too,","m"],["much of what is created, uploaded, and shared","s"],["is","v"],["humorous.",null]],
  [["The pattern","s"],["seems to be","v"],["that","c"],["first","m"],["I, as an individual,","s2"],["find","v2"],["something funny online",null],["that","c"],["may make","v2"],["me laugh or smile.",null]],
  [["Second,","m"],["as","c"],["I","s2"],["am","v2"],["alone with my laughter,",null],["I","s"],["decide","v"],["to share that same object of amusement with others,",null],["many of whom","c"],["will display","v2"],["a “like”",null],["and","c"],["possibly forward","v2"],["the message to others",null],["who","c"],["will in turn do","v2"],["likewise.",null]],
  [["So","m"],["by forwarding, sharing, and stimulating “likes” in others,","m"],["we","s"],["somehow create","v"],["a new form of collective online laughter.",null]]
 ],
 "13": [
  [["Data interpretation","s"],["in the realm of social media","m"],["is","v"],["an area",null],["fraught with ethical considerations.","m"]],
  [["In an age","m"],["where","c"],["vast amounts of user data","s2"],["are constantly being generated and collected,","v2"],["the ways","s"],["in which","c"],["this data","s2"],["is analyzed and used","v2"],["raise","v"],["important ethical questions.",null]],
  [["One key issue","s"],["is","v"],["privacy.",null]],
  [["Users","s"],["often unknowingly provide","v"],["personal information,",null],["which","c"],["is then harvested","v2"],["for data analysis.","m"]],
  [["Ethical data interpretation","s"],["in this context","m"],["requires","v"],["a commitment to respecting user privacy and ensuring",null],["that","c"],["data collection","s2"],["is","v2"],["transparent and consensual.",null]],
  [["Another ethical concern","s"],["is","v"],["the potential for bias in data interpretation.",null]],
  [["Social media platforms","s"],["are known","v"],["for their algorithms,","m"],["which","c"],["are based","v2"],["on data interpretation.","m"]],
  [["These algorithms","s"],["can perpetuate and amplify","v"],["biases",null],["present in the data,","m"],["leading to unfair outcomes, such as reinforcing stereotypes or excluding certain groups from opportunities or content.","m"]],
  [["Ensuring fairness and avoiding bias in data interpretation","s"],["is","v"],["crucial",null],["for ethical social media practices.","m"]],
  [["Furthermore,","m"],["the use of data interpretation","s"],["in influencing user behavior on social media,","m"],["such as through targeted advertising or content curation,","m"],["raises","v"],["questions about manipulation and autonomy.",null]],
  [["Ethical data practices","s"],["should involve","v"],["respecting the autonomy of users and avoiding manipulative strategies",null],["that","c"],["exploit","v2"],["user data",null],["for commercial or political gain.","m"]],
  [["Ethical data interpretation","s"],["in social media","m"],["involves","v"],["navigating complex issues of privacy, bias, fairness, and user autonomy.",null]],
  [["It","s"],["requires","v"],["a balance between leveraging data for insights and innovation,",null],["while also safeguarding the rights and interests of users.","m"]]
 ],
 "14": [
  [["Biased data","s"],["are","v"],["at the heart of discrimination,","m"],["but","c"],["deep neural networks","s"],["may intensify","v"],["the problem.",null]],
  [["Consider","v"],["a case in point.",null]],
  [["A neural network","s"],["was fed","v"],["tens of thousands of pictures of human activities",null],["and","c"],["taught","v"],["to identify the activities and the genders of those portrayed.",null]],
  [["These pictures","s"],["had","v"],["a typical gender bias,",null],["showing more men involved in outdoor activities such as driving and shooting, and more women microwaving and shopping.","m"]],
  [["When","c"],["the network","s2"],["then had to identify","v2"],["gender and activities",null],["in a new large set of pictures,","m"],["the bias","s"],["increased.","v"]],
  [["For instance,","m"],["when","c"],["the activity","s2"],["was","v2"],["cooking,",null],["67 per cent of the pictures","s"],["were","v"],["of women.",null]],
  [["The network,","s"],["however,","m"],["concluded","v"],["that","c"],["84 per cent","s2"],["were","v2"],["women,",null],["misidentifying about half of the male cooks.","m"]],
  [["Why","m"],["would","v"],["a network","s"],["intensify","v"],["discrimination?",null]],
  [["One reason","s"],["is","v"],["that","c"],["researchers","s2"],["evaluate","v2"],["a network's performance",null],["by the number of correct answers,","m"],["not by the degree to which it discriminates.","m"]],
  [["The network","s"],["can actually increase","v"],["performance",null],["by increasing discrimination.","m"]],
  [["Say","v"],["a network","s2"],["knows","v2"],["nothing",null],["except that","c"],["two-thirds of the cooks","s2"],["are","v2"],["female.",null]],
  [["To obtain the best results,","m"],["it","s"],["would guess","v"],["that","c"],["every cook","s2"],["is","v2"],["female,",null],["which","c"],["means","v2"],["that two-thirds of the answers would be correct.",null]],
  [["This,","s"],["of course,","m"],["increases","v"],["the bias",null],["to a maximum.","m"]],
  [["To avoid amplifying the bias,","m"],["the network","s"],["could randomly guess","v"],["that","c"],["the cook","s2"],["is","v2"],["a woman",null],["for two-thirds of the pictures,","m"],["and","c"],["for one-third","m"],["that","c"],["it","s2"],["is","v2"],["a man.",null]],
  [["In that case, however,","m"],["it","s"],["would get","v"],["only about 56 per cent of the answers right.",null]],
  [["In general,","m"],["if","c"],["there",null],["is","v2"],["a bias in the data,",null],["amplifying it","s"],["can lead","v"],["to better performance","m"],["than by trying to be ‘fair’.","m"]]
 ],
 "15": [
  [["Several research studies","s"],["have shown","v"],["a strong correlation between social interaction and health and well-being.",null]],
  [["Yet","m"],["there's","v"],["not much social",null],["about kids retreating to their rooms","m"],["to post selfies and comments to dozens or hundreds of followers they barely know in real life.","m"]],
  [["Social media","s"],["isn't","v"],["very social.",null]],
  [["Since","c"],["some children in elementary school","s2"],["are now being introduced","v2"],["to social media,","m"],["they","s"],["are becoming","v"],["more anxious",null],["about how many people “liked” the photo they just posted or how many “friends” or “followers” they have online.","m"]],
  [["It's","v"],["hard enough",null],["for an adult to deal with disparaging comments online — or, conversely, a lack of comments,",null],["which","c"],["we","s2"],["interpret","v2"],["as “no one is interested in me.”","m"]],
  [["Imagine","v"],["how much harder it is for children.",null]],
  [["It's","v"],["easy to say cruel things online",null],["because","c"],["you","s2"],["don't see","v2"],["the effect of your words.",null]],
  [["It's","v"],["one thing to post “No one likes you” and hit send",null],["from the comfort of your home.","m"]],
  [["It's","v"],["another thing to say the words “No one likes you”",null],["right to someone's face.","m"]],
  [["We","s"],["suggest","v"],["you","s2"],["delay","v2"],["introducing social media to your son or daughter",null],["through adolescence.","m"]],
  [["As","c"],["your child","s2"],["grows","v2"],["into a teenager,","m"],["she","s"],["needs","v"],["the firm foundation of being liked for who she is,",null],["by real people she knows.","m"]],
  [["Online popularity","s"],["is often based","v"],["on performance, appearance, and shock value.","m"]],
  [["This affection","s"],["is","v"],["conditional and misplaced.",null]],
  [["Your child","s"],["needs","v"],["to experience the unconditional love",null],["that","c"],["comes","v2"],["from you.","m"]],
  [["This love","s"],["can prevent","v"],["problems such as resentment, feelings of being disliked, guilt, fear, and insecurity.",null]],
  [["Remember,","v"],["your child","s"],["is asking","v"],["the question, “Do you like me?”",null]],
  [["By limiting social media,","m"],["you","s"],["will help","v"],["her find the answer",null],["in real people","m"],["who","c"],["care","v2"],["about her","m"],["instead of an online society","m"],["that","c"],["can be","v2"],["fickle and cruel.",null]]
 ]
};
