/* Unit 4 READ RIGHT 표기 */
module.exports = {
 "16": [
  [["When","c"],["your internal clock","s2"],["doesn't line up","v2"],["with the time at your destination,","m"],["this","s"],["can lead","v"],["to trouble.","m"]],
  [["Depending on the time zone,","m"],["you","s"],["might find","v"],["it difficult to get to sleep,",null],["or","c"],["you","s"],["may be","v"],["overwhelmingly sleepy",null],["in the middle of the day,","m"],["and","c"],["find","v"],["you're wide awake at 3 a.m.",null]],
  [["You","s"],["may suffer","v"],["jet lag",null],["if","c"],["you","s2"],["travel","v2"],["across two or more time zones","m"],["— the more you cross, the more disruption to your body clock —","m"],["but","c"],["there",null],["are","v"],["steps you can take to minimize the effects.",null]],
  [["If possible in the week or so before traveling,","m"],["start","v"],["to readjust your body clock",null],["by gradually moving your times for eating and sleeping nearer to those at your destination.","m"]],
  [["Just before the flight,","m"],["change","v"],["your watch",null],["to the time at your destination","m"],["to further readjust your body clock.","m"]],
  [["Research","s"],["has also shown","v"],["that","c"],["fasting just before and during travel","s2"],["can help","v2"],["to reset your clock,",null],["likely because","c"],["eating","s2"],["is","v2"],["a key zeitgeber — an event that cues the timing of circadian rhythms such as sleeping and waking.",null]],
  [["Jet lag","s"],["is","v"],["usually worse",null],["when traveling east:","m"],["time zones","s"],["are","v"],["ahead of your body clock,",null],["so","c"],["at bedtime","m"],["you","s2"],["are","v2"],["wide awake.",null]],
  [["It","s"],["takes","v"],["longer",null],["for the body clock to reset.","m"]],
  [["Traveling west,","m"],["time zones","s"],["are","v"],["behind your body clock,",null],["so","c"],["bedtime","s2"],["is","v2"],["later than your body expects.",null]],
  [["This","s"],["is","v"],["usually easier to adjust to than a too-early bedtime.",null]],
  [["Getting plenty of daylight at your destination and sleeping at an appropriate time for the new time zone","s"],["will help","v"],["your body clock adapt.",null]]
 ],
 "17": [
  [["Surgery","s"],["as","c"],["we","s2"],["know","v2"],["it today",null],["is","v"],["generally safe, effective, and as noninvasive as possible.",null]],
  [["For this,","m"],["we","s"],["have","v"],["the American surgeon William Halsted to thank.",null]],
  [["A giant in the history of American science,","m"],["Halsted","s"],["was born","v"],["in New York City to a wealthy family","m"],["and","c"],["earned","v"],["a medical degree from Columbia University College of Physicians and Surgeons.",null]],
  [["He","s"],["toured","v"],["Europe",null],["after leaving medical school,","m"],["absorbing new ideas about surgical practices.","m"]],
  [["When","c"],["he","s2"],["returned,","v2"],["he","s"],["became","v"],["an attending doctor and surgeon",null],["at Bellevue Hospital Medical School in New York.","m"]],
  [["He","s"],["also emerged","v"],["as one of the city's leading proponents of using cocaine as a painkiller.","m"]],
  [["Many of his experiments with the drug","s"],["were conducted","v"],["on himself and other doctors;","m"],["as a result,","m"],["Halsted","s"],["became","v"],["addicted to the drug",null],["for 2 years,","m"],["and","c"],["several of his colleagues","s"],["died.","v"]],
  [["The addiction","s"],["seriously threatened","v"],["Halsted's career,",null],["and","c"],["he","s"],["was invited","v"],["to leave New York",null],["in 1886","m"],["and","c"],["referred","v"],["to the new department of pathology at the recently opened Johns Hopkins Hospital in Baltimore,","m"],["where","c"],["he","s2"],["could work","v2"],["without having contact with patients.","m"]],
  [["Settling in Baltimore,","m"],["Halsted","s"],["beat","v"],["his cocaine addiction",null],["and","c"],["revived","v"],["his career",null],["at the newly formed Johns Hopkins University,","m"],["where","c"],["he","s2"],["became","v2"],["chief surgeon in 1890.",null]],
  [["He","s"],["began","v"],["developing a set of surgical techniques",null],["that","c"],["would be known","v2"],["as Halsted School of Surgery.","m"]],
  [["Halsted","s"],["emphasized","v"],["keeping a hygienic operating environment, using small stitches and high-quality sutures, and handling body tissues as gently as possible.",null]],
  [["His recommendations","s"],["influenced","v"],["a generation of American doctors",null],["who","c"],["trained","v2"],["at Johns Hopkins","m"],["and","c"],["spread","v2"],["his ideas",null],["throughout the medical community.","m"]]
 ],
 "18": [
  [["Viruses","s"],["are","v"],["the freeloading vampires of the body.",null]],
  [["Not a plant, animal, or bacterium,","m"],["these infectious agents","s"],["are","v"],["unable to live on their own.",null]],
  [["Instead,","m"],["they","s"],["take over","v"],["other cells",null],["to help them reproduce and carry out metabolic activities.","m"]],
  [["First identified in 1892 by the Russian scientist Dmitry I. Ivanovsky,","m"],["viruses","s"],["get","v"],["their name",null],["from the Latin word meaning “poison” and “slimy liquid.”","m"]],
  [["Today,","m"],["scientists","s"],["have identified","v"],["more than 5,000 different types of viruses.",null]],
  [["Some of them,","s"],["such as those that cause the common cold and flu,","m"],["multiply","v"],["rapidly","m"],["and","c"],["kill","v"],["the host cell,",null],["while","c"],["others,","s2"],["such as the genital herpes virus,","m"],["can remain","v2"],["inactive in the body for years.",null]],
  [["Still others,","s"],["such as the one that leads to AIDS,","m"],["are","v"],["slow viruses,",null],["meaning that they remain in the cells and reproduce slowly over years.","m"]],
  [["Essentially,","m"],["viruses","s"],["consist","v"],["of nucleic acids — either DNA or RNA —","m"],["surrounded by a protein shell.","m"]],
  [["Most viruses","s"],["are shaped","v"],["as either rods or spherical, 20-sided figures.","m"]],
  [["Because","c"],["they","s2"],["lack","v2"],["enzymes for energy production and ribosomes for protein synthesis and reproduction,",null],["viruses","s"],["attach","v"],["to a host cell.","m"]],
  [["Like a needle,","m"],["they","s"],["inject","v"],["their genetic material",null],["into the new cell.","m"]],
  [["At that point,","m"],["the viral nucleic acid","s"],["takes over","v"],["the cellular machinery,",null],["producing new virus particles.","m"]],
  [["Often,","m"],["this process","s"],["destroys","v"],["the host cell.",null]],
  [["This","s"],["releases","v"],["new viruses",null],["to infect other cells.","m"]],
  [["Because","c"],["viruses","s2"],["are stuck","v2"],["in the cells,","m"],["they're","v"],["much more difficult to kill than bacteria.",null]],
  [["Some antiviral medications","s"],["attack","v"],["viruses,",null],["while","c"],["vaccines","s2"],["are","v2"],["also effective in stimulating the immune system to produce white blood cells",null],["that","c"],["target","v2"],["specific viruses.",null]]
 ],
 "19": [
  [["Pathogenic bacteria,","s"],["such as tetanus and botulinus,","m"],["are","v"],["subsets of bacteria",null],["that","c"],["can cause","v2"],["disease",null],["in their host.","m"]],
  [["From a human perspective,","m"],["it's","v"],["difficult to see any redeeming qualities in these organisms.",null]],
  [["Fortunately,","m"],["science","s"],["has developed","v"],["crisis intervention treatments",null],["for emergencies — like stepping on a rusty nail or eating improperly preserved food","m"],["when","c"],["resistance","s2"],["is","v2"],["low.",null]],
  [["Our best bet","s"],["is","v"],["to avoid being exposed to such mischief makers and to make sure",null],["we","s2"],["eat","v2"],["correctly","m"],["so that","c"],["our vitality and resistance","s2"],["are","v2"],["high enough to repel their effects",null],["if","c"],["we","s2"],["inadvertently tangle","v2"],["with them.","m"]],
  [["Germs","s"],["don't affect","v"],["health",null],["unless","c"],["they","s2"],["are","v2"],["able to penetrate the cells of an organism — to really get into the working parts.",null]],
  [["They","s"],["can't do","v"],["this",null],["unless","c"],["the body's vitality and resistance","s2"],["are weakened.","v2"]],
  [["When","c"],["that","s2"],["happens,","v2"],["cells","s"],["become","v"],["more vulnerable to invaders.",null]],
  [["Accidents, poor nutrition, extreme fatigue, or intense stress","s"],["can all lower","v"],["resistance.",null]],
  [["Short-term, high-intensity events of an accident, or longer-term, non-stop abuse of a destructive lifestyle","s"],["disrupts","v"],["the normal function of the body as a whole, as well as the cells",null],["that","c"],["make up","v2"],["that whole.",null]],
  [["The strategy","s"],["for avoiding infectious disease","m"],["is not","v"],["to kill off all bacteria",null],["to avoid illness.","m"]],
  [["The best course","s"],["is","v"],["to make sure",null],["your cells","s2"],["are","v2"],["healthy enough to keep your vitality at its peak.",null]],
  [["How vital","m"],["are","v"],["your cells?","s"]],
  [["How “alive”","m"],["are","v"],["you?","s"]],
  [["Your health, vitality, and resistance to disease","s"],["are determined","v"],["by the health of your cells.","m"]]
 ],
 "20": [
  [["It","s"],["is","v"],["our belief",null],["that","c"],["the nature of medical education","s2"],["has fundamentally changed","v2"],["in the last two or three decades","m"],["as","c"],["has","v2"],["the nature of the practice of medicine.","s2"]],
  [["It","s"],["would be","v"],["odd",null],["if","c"],["that","s2"],["were not","v2"],["the case,",null],["as","c"],["education","s2"],["needs","v2"],["to evolve",null],["to provide the skills needed by practitioners to function safely and effectively in a changing healthcare environment.","m"]],
  [["The reasons for change","s"],["are","v"],["complex.",null]],
  [["What we do know","s"],["unfortunately","m"],["is","v"],["that","c"],["levels of burnout, emotional distress, and substance misuse","s2"],["are","v2"],["very high",null],["amongst medical students","m"],["wherever","c"],["one","s2"],["goes","v2"],["in the world.","m"]],
  [["This situation","s"],["mirrors","v"],["the one",null],["found amongst doctors of all grades working in different healthcare systems and cultures.","m"]],
  [["Training for and practising medicine","s"],["have always been","v"],["stressful,",null],["but","c"],["increased complexity in investigations, interventions, and management,","s"],["along with societal changes and higher patient expectations","m"],["has contributed","v"],["to increasing levels of stress and distress.","m"]],
  [["The big unknown","s"],["is","v"],["to what extent this is a developing phenomenon.",null]],
  [["Attempts to measure and identify distress and burnout in medical students","s"],["have been","v"],["fairly limited",null],["until recent years,","m"],["so","c"],["historical comparisons","s2"],["are","v2"],["generally not possible.",null]],
  [["There",null],["has been","v"],["more research",null],["among practising doctors,","m"],["and","c"],["that","s"],["does indeed suggest","v"],["a worsening over time.",null]],
  [["It","s"],["seems","v"],["reasonable",null],["to extrapolate",null],["that","c"],["the same","s2"],["will be occurring","v2"],["in students.","m"]]
 ]
};
