/* Unit 8 READ RIGHT 표기 */
module.exports = {
 "36": [
  [["When","c"],["a country","s2"],["is","v2"],["in a recession,","m"],["should","v"],["its government","s"],["spend","v"],["more money or less?",null]],
  [["On a surface level,","m"],["there",null],["are","v"],["good arguments",null],["for each.","m"]],
  [["The best argument","s"],["for spending more money to get out of a bad economic situation","m"],["was","v"],["the 1930s Great Depression in the United States,",null],["where","c"],["massively increased federal spending","s2"],["under President Franklin D. Roosevelt","m"],["appeared","v2"],["to guide the economy back on track",null],["by loaning public-sector money into the private sector to create jobs and promote social welfare.","m"]],
  [["This","s"],["is","v"],["traditionally","m"],["the approach",null],["favored by the British economist John Maynard Keynes,","m"],["whose","c"],["overall system,","s2"],["referred to as Keynesian economics,","m"],["is","v2"],["the most widely accepted economic philosophy",null],["in Western academic circles.","m"]],
  [["Neoliberalism","s"],["favors","v"],["an alternate approach",null],["called austerity.","m"]],
  [["Inspired by supply-side economics,","m"],["austerity","s"],["operates","v"],["on the belief","m"],["that","c"],["if","c"],["you","s2"],["cut","v2"],["taxes,",null],["especially for investors and corporations,","m"],["it","s2"],["will increase","v2"],["private-sector spending and investment,",null],["precluding the need for dramatic government intervention.","m"]],
  [["Of course,","m"],["in order to cut taxes","m"],["you","s"],["need","v"],["to decrease government spending.",null]],
  [["This","s"],["creates","v"],["an unpopular situation",null],["where","c"],["a large number of people,","s2"],["already driven into poverty during a recession,","m"],["find","v2"],["that","c"],["their government support system","s2"],["is also getting","v2"],["smaller.",null]],
  [["Austerity","s"],["hasn't produced","v"],["a clear success story",null],["yet.","m"]],
  [["History","s"],["has shown","v"],["so far","m"],["that","c"],["investors","s2"],["tend","v2"],["to hold on to their money",null],["during recessions,","m"],["which","c"],["are also not generally regarded","v2"],["as ideal times for private corporations to dramatically expand their workforce.","m"]],
  [["But","c"],["neoliberals","s"],["continue","v"],["to experiment with different austerity policies,",null],["looking for a private-sector, supply-side solution to recessions","m"],["that","c"],["can rescue","v2"],["an economy",null],["without increasing taxes or the size of the government.","m"]]
 ],
 "37": [
  [["Covering the president","s"],["has become","v"],["an industry unto itself.",null]],
  [["Hundreds of “beat reporters”","s"],["— journalists","m"],["who","c"],["cover","v2"],["the White House",null],["on a daily basis —","m"],["work","v"],["from the basement of the White House.","m"]],
  [["Twice a day,","m"],["these reporters","s"],["meet","v"],["with the president's press secretary","m"],["to get a briefing on the day's activities.","m"]],
  [["Television cameras","s"],["covering these briefings","m"],["have been","v"],["a frequent source of conflict",null],["between the press secretary and the press,","m"],["as","c"],["some journalists","s2"],["use","v2"],["these press briefings",null],["as an opportunity to grandstand for the cameras.","m"]],
  [["Typically,","m"],["the press","s"],["is","v"],["on call",null],["twenty-four hours a day,","m"],["unless","c"],["the press secretary","s2"],["puts","v2"],["a “lid”",null],["on the news,","m"],["which","c"],["means","v2"],["that","c"],["no big announcements","s2"],["are planned.","v2"]],
  [["Most presidents","s"],["have “feuded”","v"],["with particular journalists and publications","m"],["at one time or another.","m"]],
  [["Richard Nixon","s"],["disliked","v"],["the Washington Post and New York Times,",null],["and","c"],["had","v"],["his vice president publicly attack them.",null]],
  [["The Clinton White House","s"],["singled out","v"],["Sue Schmidt of the Washington Post",null],["as a reporter with a vendetta against the president.","m"]],
  [["President George W. Bush","s"],["publicly used","v"],["a rude word",null],["to describe New York Times reporter Adam Clymer,","m"],["a sentiment","m"],["that","c"],["Vice President Cheney","s2"],["agreed with.","v2"]],
  [["President Kennedy,","s"],["on the other hand,","m"],["enjoyed","v"],["a friendly relationship",null],["with the press corps,","m"],["partly","m"],["because","c"],["he","s2"],["singled out","v2"],["favorites",null],["for special treatment in return for favorable coverage.","m"]],
  [["In spite of the tension between the president and the press corps,","m"],["the two","s"],["have","v"],["a symbiotic relationship.",null]],
  [["The president","s"],["needs","v"],["the press to deliver his message,",null],["and","c"],["the press","s"],["needs","v"],["access to the president",null],["in order to do its job.","m"]],
  [["It's","v"],["not uncommon",null],["for White House staffers to leak information to select journalists","s"],["in order to shape the coverage.","m"]],
  [["Sometimes","m"],["the president","s"],["will grant","v"],["exclusive interviews",null],["to certain reporters","m"],["as a way to dominate the headlines.","m"]]
 ],
 "38": [
  [["The History of the Kings of Britain","s"],["laid","v"],["the groundwork",null],["that","c"],["future Arthurian writers,","s2"],["such as Marie de France and Sir Thomas Malory,","m"],["would build upon,","v2"],["with Monmouth defining King Arthur's personality and family history, as well as his strong ties to Merlin.","m"]],
  [["Still, eventually,","m"],["The History","s"],["began","v"],["to fall out of favour,",null],["as","c"],["scholars","s2"],["started","v2"],["to realize",null],["how much of a massive jump in logic","s2"],["needed to be taken","v2"],["to read the whole book at face value.","m"]],
  [["In 1718,","m"],["one Aaron Thompson","s"],["published","v"],["the first English translation of The History",null],["and","c"],["was","v"],["so worried",null],["that","c"],["by reprinting Monmouth's writing","m"],["he'd be opening","v2"],["a Pandora's box of misinformation",null],["that","c"],["he","s2"],["included","v2"],["a large tome of an introduction,",null],["going to great pains to remind the reader","m"],["that","c"],["The History","s2"],["is:","v2"],["‘barbarous and in many places unclear’.",null]],
  [["We'll","v"],["likely never","m"],["know","v"],["why","c"],["Geoffrey of Monmouth","s2"],["included","v2"],["so much fabrication",null],["in his history of Britain.","m"]],
  [["Still,","m"],["it's","v"],["perhaps","m"],["one of history's most impressive lies",null],["and","c"],["still","m"],["impacts","v"],["our lives",null],["today.","m"]],
  [["The debate","s"],["on whether King Arthur was real","m"],["rages on,","v"],["though with little concrete evidence","m"],["that","c"],["he","s2"],["was.","v2"]],
  [["Interestingly though,","m"],["there",null],["are","v"],["accounts of a ninth-century warlord and tenth-century Welsh leader with that name,",null],["which","c"],["is","v2"],["possibly","m"],["where","c"],["Monmouth","s2"],["got","v2"],["the inspiration for his fictional version.",null]],
  [["Slightly redundant historic arguments aside,","m"],["the cultural legacy of The History","s"],["is","v"],["almost as unbelievable as its source material,",null],["spanning two Shakespeare plays, as well as countless books, films, and TV shows","m"],["that","c"],["have built","v2"],["on the Arthurian legend.","m"]],
  [["Geoffrey of Monmouth","s"],["may still be seen","v"],["by many","m"],["to be a pseudo-historian,",null],["but","c"],["his lies","s"],["make","v"],["him perhaps one of the greatest fiction writers of all time.",null]]
 ],
 "39": [
  [["It's","v"],["easy",null],["to romanticize the hunter-gatherer way of life","s"],["as a Huckleberry Finn existence","m"],["filled with adventure and hunting expeditions,","m"],["lived in small, close-knit communities in an unspoiled world.","m"]],
  [["But,","c"],["in actual fact,","m"],["there",null],["is","v"],["much",null],["to suggest","m"],["that","c"],["our ancestors' lives","s2"],["were","v2"],["in many ways","m"],["complete hell.",null]],
  [["The average life expectancy","s"],["was","v"],["around 30 years,",null],["which","c"],["isn't","v2"],["to say",null],["that","c"],["everyone","s2"],["would drop","v2"],["dead",null],["at 30,","m"],["but","c"],["that","c"],["many","s2"],["died","v2"],["young.",null]],
  [["As many as half","s"],["died","v"],["before","c"],["they","s2"],["reached","v2"],["their teens",null],["— normally during birth or of an infection.","m"]],
  [["Those","s"],["who","c"],["did make","v2"],["it to adulthood",null],["lived","v"],["with the imminent threat of starvation, blood loss, dehydration, animal attacks, even more infections, accidents, and murder.","m"]],
  [["Only a fraction","s"],["would have made","v"],["it",null],["to today's retirement age","m"],["and","c"],["yes,","m"],["there",null],["were","v"],["hunter-gatherers",null],["who","c"],["lived","v2"],["to be 70 or even 80.","m"]],
  [["So","c"],["old age","s"],["in itself","m"],["is","v"],["nothing new,",null],["but","c"],["the fact","s"],["that","c"],["so many people","s2"],["are now reaching","v2"],["it",null],["is.","v"]],
  [["Around 10,000 years ago,","m"],["probably","m"],["the single most significant shift in our ancestors' way of life","s"],["occurred:","v"],["we","s"],["became","v"],["farmers.",null]],
  [["But","c"],["spears and bows","s"],["weren't replaced","v"],["by plows","m"],["overnight;","m"],["this gradual transition from a nomadic to an agricultural lifestyle","s"],["took place","v"],["over the course of centuries.","m"]],
  [["The farmers' living conditions","s"],["can be summarized","v"],["quite simply:","m"],["an even greater hell.",null]],
  [["The average life expectancy of around 30 years and the ever-present threat of death","s"],["remained","v"],["unchanged,",null],["although perhaps with a lesser risk of starvation.","m"]],
  [["Instead,","m"],["murder","s"],["became","v"],["an increasingly common cause of death,",null],["presumably","m"],["because","c"],["improved means of storing food and harvesting resources","s2"],["meant","v2"],["there",null],["was","v2"],["more to fight over.",null]],
  [["Hierarchies","s"],["became","v"],["more pronounced,",null],["and","c"],["on top of that,","m"],["a number of contagious diseases","s"],["appeared","v"],["on the scene.","m"]],
  [["Work tasks","s"],["grew","v"],["more monotonous",null],["and","c"],["working hours","s"],["longer.",null]],
  [["Diets","s"],["became","v"],["less varied,",null],["most likely consisting of cereals for breakfast, lunch, and dinner.","m"]]
 ],
 "40": [
  [["Before 1765,","m"],["Samuel Adams","s"],["labored","v"],["under the belief","m"],["that","c"],["well-reasoned arguments","s2"],["would be","v2"],["enough to convince the colonists of the rightness of his cause.",null]],
  [["But","c"],["as","c"],["the years of failure","s2"],["piled up,","v2"],["he","s"],["confronted","v"],["the reality",null],["that","c"],["the colonists","s2"],["retained","v2"],["a deep emotional attachment to England,",null],["as","c"],["children","s2"],["do","v2"],["to a parent.","m"]],
  [["Liberty","s"],["meant","v"],["less",null],["to them","m"],["than","c"],["did","v2"],["England's provision of protection and a sense of belonging in a threatening environment.","s2"]],
  [["When","c"],["Adams","s2"],["realized","v2"],["this,",null],["he","s"],["reformulated","v"],["his goals:",null],["instead of preaching independence and the ideas of John Locke,","m"],["he","s"],["set","v"],["to work to cut the colonists' ties with England.","m"]],
  [["He","s"],["made","v"],["the children distrust the parent,",null],["whom","c"],["they","s2"],["came","v2"],["to see",null],["not as a protector but as an oppressive overlord","m"],["exploiting them for its profit.","m"]],
  [["As","c"],["the bond with England","s2"],["loosened,","v2"],["Adams's arguments for independence","s"],["began","v"],["to resonate.",null]],
  [["Now","m"],["the colonists","s"],["began","v"],["to look for their sense of identity",null],["not to Mother England but to themselves.","m"]],
  [["With the Stamp Act campaign, then,","m"],["Adams","s"],["discovered","v"],["strategy,",null],["the bridge between his ideas and reality.","m"]],
  [["His writings","s"],["now","m"],["aimed","v"],["at stirring up anger.","m"]],
  [["The demonstrations","s"],["he","s2"],["organized","v2"],["— pure theater —","m"],["were also designed","v"],["to create and build anger",null],["among the middle and lower classes,","m"],["key components of the future revolution.","m"]],
  [["Adams's innovative use of boycotts","s"],["was intended","v"],["to provoke the British and bait them into rash action.",null]],
  [["Their violent response","s"],["contrasted","v"],["brilliantly","m"],["with the relatively peaceful methods of the colonists,","m"],["making them seem as tyrannical","m"],["as","c"],["he","s2"],["had said","v2"],["they were.",null]],
  [["Adams","s"],["also worked","v"],["to stir dissension among the English themselves,","m"],["weakening the bond on all sides.","m"]],
  [["The Stamp Act and Tea Act","s"],["were","v"],["actually rather trivial,",null],["but","c"],["Adams","s"],["strategically manipulated","v"],["them",null],["to manufacture outrage,","m"],["making them into wedges driven between the two sides.","m"]]
 ]
};
